// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zamm.Infrastructure.DataContext;

#nullable disable

namespace Zamm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224081627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zamm.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("OffPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_Address_Country");

                    b.HasIndex("Suburb")
                        .HasDatabaseName("IX_Address_Suburb");

                    b.HasIndex("Postcode", "State")
                        .HasDatabaseName("IX_Address_Postcode_State");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AddressOffPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInvestment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUnencumbered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RentalAgentContact")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RentalHasAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RentalIncomeFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RentalIncomeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValuationDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ValueIsCertified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ZoningType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("IX_Asset_AddressId");

                    b.HasIndex("IsInvestment")
                        .HasDatabaseName("IX_Asset_IsInvestment");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Asset_Name");

                    b.HasIndex("PropertyType")
                        .HasDatabaseName("IX_Asset_PropertyType");

                    b.HasIndex("ValuationDate")
                        .HasDatabaseName("IX_Asset_ValuationDate");

                    b.HasIndex("IsUnencumbered", "Value")
                        .HasDatabaseName("IX_Asset_Unencumbered_Value");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.AssetCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Ownership percentage (0-100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_AssetCompany_AssetId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_AssetCompany_CompanyId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_AssetCompany_DeletedAt");

                    b.HasIndex("AssetId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetCompany_AssetId_CompanyId_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("asset_companies", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.AssetPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Ownership percentage (0-100)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_AssetPerson_AssetId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_AssetPerson_DeletedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_AssetPerson_PersonId");

                    b.HasIndex("AssetId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetPerson_AssetId_PersonId_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("asset_people", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Brokerage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorisedDomain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMasterAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorisedDomain")
                        .HasDatabaseName("IX_Brokerage_AuthorisedDomain");

                    b.HasIndex("IsMasterAccount")
                        .HasDatabaseName("IX_Brokerage_IsMasterAccount");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Brokerage_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Brokerage_Slug");

                    b.ToTable("brokerages", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.BrokerageLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrokerageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageId")
                        .HasDatabaseName("IX_BrokerageLogo_BrokerageId");

                    b.ToTable("brokerage_logos", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Acn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ActingOnTrust")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsContactExistingPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneWork")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("TradingName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrustName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Abn")
                        .HasDatabaseName("IX_Company_Abn");

                    b.HasIndex("Acn")
                        .HasDatabaseName("IX_Company_Acn");

                    b.HasIndex("ActingOnTrust")
                        .HasDatabaseName("IX_Company_ActingOnTrust");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("IX_Company_AddressId");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("IX_Company_BrokerId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Company_Email");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Company_Name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.CompanyPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_CompanyPerson_CompanyId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_CompanyPerson_DeletedAt");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_CompanyPerson_PersonId");

                    b.HasIndex("CompanyId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_CompanyPerson_CompanyId_PersonId_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("company_people", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.ConfirmEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ConfirmEmail_ConfirmCode");

                    b.HasIndex("ExpiryTime")
                        .HasDatabaseName("IX_ConfirmEmail_ExpiryTime");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ConfirmEmail_UserId");

                    b.HasIndex("UserId", "IsConfirmed")
                        .HasDatabaseName("IX_ConfirmEmail_UserId_IsConfirmed");

                    b.ToTable("confirm_emails", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDismissed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRepeating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LiabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedValuesObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RepeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("RepeatUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RepeatingDateDismissed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("IX_Event_AddedByUserId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Event_CompanyId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Event_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Event_DeletedAt");

                    b.HasIndex("LiabilityId")
                        .HasDatabaseName("IX_Event_LiabilityId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_Event_PersonId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Event_Type");

                    b.HasIndex("IsDismissed", "Date")
                        .HasDatabaseName("IX_Event_IsDismissed_Date");

                    b.HasIndex("IsRepeating", "Date")
                        .HasDatabaseName("IX_Event_IsRepeating_Date");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.EventFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_EventFile_DeletedAt");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EventFile_EventId");

                    b.ToTable("event_files", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.FixedRatePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("CustomRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_FixedRatePeriod_DeletedAt");

                    b.HasIndex("LiabilityId")
                        .HasDatabaseName("IX_FixedRatePeriod_LiabilityId");

                    b.HasIndex("LiabilityId", "StartDate")
                        .HasDatabaseName("IX_FixedRatePeriod_LiabilityId_StartDate");

                    b.ToTable("fixed_rate_periods", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.InterestRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("IX_InterestRate_LoanId");

                    b.HasIndex("RateType")
                        .HasDatabaseName("IX_InterestRate_RateType");

                    b.HasIndex("LoanId", "CreatedAt")
                        .HasDatabaseName("IX_InterestRate_LoanId_CreatedAt");

                    b.ToTable("interest_rates", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrokerageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageId")
                        .HasDatabaseName("IX_Invitation_BrokerageId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Invitation_Email");

                    b.HasIndex("InviterId")
                        .HasDatabaseName("IX_Invitation_InviterId");

                    b.HasIndex("IsComplete", "CreatedAt")
                        .HasDatabaseName("IX_Invitation_IsComplete_CreatedAt");

                    b.HasIndex("Email", "BrokerageId", "IsComplete")
                        .HasDatabaseName("IX_Invitation_Email_BrokerageId_IsComplete");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Lender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Lender_DeletedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Lender_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Lender_Slug_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("lenders", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Liability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccountBsb")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("FinancePurpose")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("InitialBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InterestOnlyTerm")
                        .HasColumnType("int");

                    b.Property<decimal?>("IntroRatePercent")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("IntroRateYears")
                        .HasColumnType("int");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LoanTerm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OffsetAccountBsb")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OffsetAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RepaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RepaymentFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SettlementRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FinancePurpose")
                        .HasDatabaseName("IX_Liability_FinancePurpose");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("IX_Liability_LoanId");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Liability_StartDate");

                    b.ToTable("liabilities", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.LiabilityAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_LiabilityAsset_AssetId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_LiabilityAsset_DeletedAt");

                    b.HasIndex("LiabilityId")
                        .HasDatabaseName("IX_LiabilityAsset_LiabilityId");

                    b.HasIndex("LiabilityId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("IX_LiabilityAsset_LiabilityId_AssetId_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("liability_assets", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.LiabilityCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_LiabilityCompany_CompanyId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_LiabilityCompany_DeletedAt");

                    b.HasIndex("LiabilityId")
                        .HasDatabaseName("IX_LiabilityCompany_LiabilityId");

                    b.HasIndex("LiabilityId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("IX_LiabilityCompany_LiabilityId_CompanyId_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("liability_companies", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.LiabilityPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_LiabilityPerson_DeletedAt");

                    b.HasIndex("LiabilityId")
                        .HasDatabaseName("IX_LiabilityPerson_LiabilityId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_LiabilityPerson_PersonId");

                    b.HasIndex("LiabilityId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_LiabilityPerson_LiabilityId_PersonId_Unique")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("liability_people", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Loan_DeletedAt");

                    b.HasIndex("LenderId")
                        .HasDatabaseName("IX_Loan_LenderId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Loan_Name");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LiabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Note_AuthorId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Note_CompanyId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Note_CreatedAt");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Note_DeletedAt");

                    b.HasIndex("EditedById");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_Note_EventId");

                    b.HasIndex("LiabilityId")
                        .HasDatabaseName("IX_Note_LiabilityId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_Note_PersonId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Permissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_Permissions_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Permissions_UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_UserId_RoleId_Unique");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActingOnTrust")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NotifyOfBirthday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneMobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhonePreference")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneWork")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SpouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrustName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActingOnTrust")
                        .HasDatabaseName("IX_Person_ActingOnTrust");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("IX_Person_AddressId");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("IX_Person_BrokerId");

                    b.HasIndex("DateOfBirth")
                        .HasDatabaseName("IX_Person_DateOfBirth");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Person_Email");

                    b.HasIndex("SpouseId")
                        .HasDatabaseName("IX_Person_SpouseId");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Person_FirstName_LastName");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryTime")
                        .HasDatabaseName("IX_RefreshToken_ExpiryTime");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshToken_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.HasIndex("UserId", "IsRevoked", "ExpiryTime")
                        .HasDatabaseName("IX_RefreshToken_UserId_IsRevoked_ExpiryTime");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Role_RoleCode");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("IX_Role_RoleName");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("BrokerageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasOnboarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageId")
                        .HasDatabaseName("IX_User_BrokerageId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_User_UserName");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.AssetCompany", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetCompanies")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Company", "Company")
                        .WithMany("AssetCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.AssetPerson", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetPeople")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Person", "Person")
                        .WithMany("AssetPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.BrokerageLogo", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Brokerage", "Brokerage")
                        .WithMany("Logos")
                        .HasForeignKey("BrokerageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brokerage");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Company", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.User", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.CompanyPerson", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Company", "Company")
                        .WithMany("CompanyPeople")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Person", "Person")
                        .WithMany("CompanyPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.ConfirmEmail", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.User", "User")
                        .WithMany("ConfirmEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Event", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.Liability", "Liability")
                        .WithMany()
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedByUser");

                    b.Navigation("Company");

                    b.Navigation("Liability");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.EventFile", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Event", "Event")
                        .WithMany("Files")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.FixedRatePeriod", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Liability", "Liability")
                        .WithMany("FixedRatePeriods")
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liability");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.InterestRate", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Loan", "Loan")
                        .WithMany("InterestRates")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Brokerage", "Brokerage")
                        .WithMany("Invitations")
                        .HasForeignKey("BrokerageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brokerage");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Liability", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Loan", "Loan")
                        .WithMany("Liabilities")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.LiabilityAsset", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Asset", "Asset")
                        .WithMany("LiabilityAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Liability", "Liability")
                        .WithMany("LiabilityAssets")
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Liability");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.LiabilityCompany", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Company", "Company")
                        .WithMany("LiabilityCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Liability", "Liability")
                        .WithMany("LiabilityCompanies")
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Liability");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.LiabilityPerson", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Liability", "Liability")
                        .WithMany("LiabilityPeople")
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Person", "Person")
                        .WithMany("LiabilityPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liability");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Loan", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Lender", "Lender")
                        .WithMany("Loans")
                        .HasForeignKey("LenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lender");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Note", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.User", "EditedBy")
                        .WithMany()
                        .HasForeignKey("EditedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zamm.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.Liability", "Liability")
                        .WithMany()
                        .HasForeignKey("LiabilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Company");

                    b.Navigation("EditedBy");

                    b.Navigation("Event");

                    b.Navigation("Liability");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Permissions", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Person", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zamm.Domain.Entities.User", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zamm.Domain.Entities.Person", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Broker");

                    b.Navigation("Spouse");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.User", b =>
                {
                    b.HasOne("Zamm.Domain.Entities.Brokerage", "Brokerage")
                        .WithMany("Users")
                        .HasForeignKey("BrokerageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brokerage");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetCompanies");

                    b.Navigation("AssetPeople");

                    b.Navigation("LiabilityAssets");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Brokerage", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Logos");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Company", b =>
                {
                    b.Navigation("AssetCompanies");

                    b.Navigation("CompanyPeople");

                    b.Navigation("LiabilityCompanies");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Event", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Lender", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Liability", b =>
                {
                    b.Navigation("FixedRatePeriods");

                    b.Navigation("LiabilityAssets");

                    b.Navigation("LiabilityCompanies");

                    b.Navigation("LiabilityPeople");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Loan", b =>
                {
                    b.Navigation("InterestRates");

                    b.Navigation("Liabilities");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Person", b =>
                {
                    b.Navigation("AssetPeople");

                    b.Navigation("CompanyPeople");

                    b.Navigation("LiabilityPeople");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Zamm.Domain.Entities.User", b =>
                {
                    b.Navigation("ConfirmEmails");

                    b.Navigation("Permissions");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
